"""跨资产根身份、交易场所、日历、基金/衍生品与 `P0` 市场事实模型。

本域先区分法律实体、可交易工具、交易场所和来源观察，再保存双时态 `revision`；股票、`ETF`、
指数、期货、期权、两融和港通不能因为代码或名称相似而绕过这些身份边界。
"""

from .derivative_revisions import DerivativeContractRevision, DerivativeDailyBarRevision
from .equity_expansion import (
    BlockTradeExecutionRevision,
    BusinessCompositionLabelVersion,
    BusinessCompositionLine,
    BusinessCompositionReportRevision,
    CorporateEarningsValue,
    CorporateEvent,
    CorporateEventRevision,
    DisclosureDocument,
    DisclosureDocumentRelation,
    DragonTigerEventRevision,
    DragonTigerSeatItem,
    RestrictedUnlockLot,
    ShareCapitalComponent,
    ShareholderHoldingAction,
    TradingDisclosureReasonMapVersion,
)
from .identity import (
    DerivativeContract,
    DerivativeProduct,
    EtfListing,
    FundLegalEntity,
    FundShareClass,
    InstrumentIdentifierVersion,
    InstrumentLifecycleVersion,
    MarketCalendarDay,
    MarketEntity,
    MarketEntityRelationVersion,
    MarketInstrument,
    MarketSessionVersion,
    TradingVenue,
)
from .margin_stock_connect import (
    MarginEligibilityRevision,
    MarginMarketDailyRevision,
    MarginSecurityDailyRevision,
    MarginSystemRiskDailyRevision,
    StockConnectActiveSecurityRevision,
    StockConnectChannelDailyRevision,
    StockConnectDisclosureRegime,
    StockConnectHoldingItem,
    StockConnectHoldingSnapshot,
)
from .overview import (
    MarketOverviewActiveBundle,
    MarketOverviewBundle,
    MarketOverviewBundleComponent,
    MarketOverviewComponentRelease,
    MarketOverviewCurrentPointer,
    MarketOverviewDerivationInputPointer,
    MarketOverviewPointerTransition,
)
from .stock_connect_center import (
    StockConnectBundlePublication,
    StockConnectBundleRollbackAudit,
    StockConnectCalendarObservation,
    StockConnectChannelStatusRevision,
    StockConnectOverviewPublication,
)
from .stock_connect_identity import StockConnectHkexInstrumentIdentity
from .stock_connect_overview_generation import (
    StockConnectOverviewGeneration,
    StockConnectOverviewGenerationComponent,
)
from .stock_connect_readiness import (
    StockConnectReadinessCalendarDay,
    StockConnectReadinessSnapshot,
)

__all__ = [
    "DerivativeContract",
    "DerivativeContractRevision",
    "DerivativeDailyBarRevision",
    "DerivativeProduct",
    "BlockTradeExecutionRevision",
    "BusinessCompositionLabelVersion",
    "BusinessCompositionLine",
    "BusinessCompositionReportRevision",
    "CorporateEarningsValue",
    "CorporateEvent",
    "CorporateEventRevision",
    "DisclosureDocument",
    "DisclosureDocumentRelation",
    "DragonTigerEventRevision",
    "DragonTigerSeatItem",
    "EtfListing",
    "FundLegalEntity",
    "FundShareClass",
    "InstrumentIdentifierVersion",
    "InstrumentLifecycleVersion",
    "MarketCalendarDay",
    "MarketEntity",
    "MarketEntityRelationVersion",
    "MarketInstrument",
    "MarketOverviewActiveBundle",
    "MarketOverviewBundle",
    "MarketOverviewBundleComponent",
    "MarketOverviewComponentRelease",
    "MarketOverviewCurrentPointer",
    "MarketOverviewDerivationInputPointer",
    "MarketOverviewPointerTransition",
    "MarketSessionVersion",
    "MarginEligibilityRevision",
    "MarginMarketDailyRevision",
    "MarginSecurityDailyRevision",
    "MarginSystemRiskDailyRevision",
    "StockConnectActiveSecurityRevision",
    "StockConnectBundleRollbackAudit",
    "StockConnectBundlePublication",
    "StockConnectCalendarObservation",
    "StockConnectChannelDailyRevision",
    "StockConnectChannelStatusRevision",
    "StockConnectOverviewPublication",
    "StockConnectDisclosureRegime",
    "StockConnectHoldingItem",
    "StockConnectHoldingSnapshot",
    "StockConnectHkexInstrumentIdentity",
    "StockConnectOverviewGeneration",
    "StockConnectOverviewGenerationComponent",
    "StockConnectReadinessCalendarDay",
    "StockConnectReadinessSnapshot",
    "RestrictedUnlockLot",
    "ShareCapitalComponent",
    "ShareholderHoldingAction",
    "TradingVenue",
    "TradingDisclosureReasonMapVersion",
]
